### ISSUE TITLE
Automate schedule generation

### ISSUE THREAD

**Issue by WJBarnes456** [CUAMS/CUAMS-Website#1]
At the very least, we need to be able to generate a basic schedule given total user input.

Essential flow:
* User enters term dates, and a list of shows with episode counts
* System works out the dates for each meeting, and assigns shows across that time period
* System exports this to a YAML file that can be directly printed onto the webpage

Other useful features include:
* Automatically fetch metadata - so put a MAL/AniList link in instead of the series title, and use that to fetch the episode count etc automatically
* Automatically fetch university term dates - we can just scrape the webpage for this, otherwise there's almost certainly an API that hosts it. Cam is good at things like that.
* Fetch photos at the same time

**Comment by SamG97** [comment]
If you're especially bored, it would also be cool if we could update a Google calendar with the meeting times / details that is shared publicly so that users can easily copy all meeting details to their own personal calendar.

The complexity involved in setting up OAuth to access a Google calendar is likely to be too much effort to be worth it though.

**Comment by WJBarnes456** [comment]
I want to make sure there's something usable for generating the 2019/20 schedule. Things that are left to do here are:
- Automatically generate a (skeleton) meetings.yaml as well, for added ease
- Improve project structure; now there are classes, we probably don't want just one massive file. Imports would be nice.
- Improve the distribution of episodes; the current method works pretty well as a skeleton but it'd be nice to have a better way of distributing them. Maybe even move episodes between meetings?

Honestly this need would be best served by a web app that we could just statically serve on the website on, like, https://cuams.soc.srcf.net/schedule-planner or something. This is unneeded complexity, so I probably won't be the one doing that (if anyone)

**Comment by WJBarnes456** [comment]
Ben successfully automated meetings.yml generation (see ad0839c9), including fetching photos.

These could probably be integrated together to simultaneously create the meetings.yml and schedule.yml files; I will open this as a new issue.
